config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resources :statuses

  get "admin", to: "admin#index"

  namespace :admin do
    resources :users do
      member do
        post :resend_activation_email
      end
    end
  end

  get "signup", to: "signup#new"
  post "signup", to: "signup#create"
  get "signup/:id/confirm_email", to: "signup#confirm_email", as: :confirm_email_signup

  root "support#index"
  get "support/home", to: "support#index"
  get "support", to: redirect("support/home")

  namespace :support do
    resources :tickets, only: [ :index, :create, :new, :edit, :show, :update ] do
      resources :comments, only: [ :create ]
    end
  end

  get "workspace/dashboard", to: "workspace#index"
  get "workspace", to: redirect("workspace/dashboard")

  namespace :workspace do
    resources :tickets, only: [ :index, :create, :new, :edit, :show, :update, :destroy ] do
      resources :comments, only: [ :create ]
    end
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :status
  belongs_to :requester, class_name: "User", foreign_key: "requester_id"
  belongs_to :assigned_agent, class_name: "User", foreign_key: "assigned_agent_id", optional: true

  validate :assigned_agent_exists_with_valid_role

  validates :title, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 9810 }
  validates :status, presence: true

  private

  def assigned_agent_exists_with_valid_role
    return if assigned_agent_id.nil? # Allow nil values

    unless User.exists?(id: assigned_agent_id)
      errors.add(:assigned_agent_id, "must be a valid user")
      return
    end

    unless User.find(assigned_agent_id).role.name == "Support Agent"
      errors.add(:assigned_agent_id, "must have the 'Support Agent' role")
    end
  end
end

app/controllers/support/comments_controller.rb
class Support::CommentsController < SupportController
  before_action :require_authentication
  before_action :set_ticket, only: %i[ create ]
  before_action :authorize_access, only: %i[ create ]

  def create
    @ticket = Ticket.find(params[:ticket_id])
    @comment = @ticket.comments.build(comment_params)
    @comment.user_id = Current.user.id

    if @comment.save
      respond_to do |format|
          format.html { redirect_to support_ticket_path(@ticket), notice: "Post was successfully created." }
          format.turbo_stream
      end
      TicketMailer.requester_replied(@ticket).deliver if @ticket.assigned_agent_id
    else
      @comments = @ticket.comments
      redirect_to support_ticket_path(@ticket), status: :unprocessable_entity
    end
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end

  def authorize_access
    unless UserPolicy.new.can_access_ticket?(@ticket)
      render file: "public/404.html", status: :forbidden
    end
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/support/tickets_controller.rb
class Support::TicketsController < SupportController
  before_action :require_authentication
  before_action :set_ticket, only: %i[ show edit update ]
  before_action :authorize_ticket_access, only: %i[ show edit update ]

  def index
    @tickets = Ticket.where(requester_id: Current.user.id).order(:id).page(params[:page]).per(10)
  end

  def show
    @ticket = Ticket.find(params[:id])
    @comments = @ticket.comments.all.includes(:user)
    @comment = @ticket.comments.build
  end

  def new
    @ticket = Ticket.new
  end

  def edit
  end

  def update
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.status_id = Status.find_by(name: "Open").id
    @ticket.requester_id = Current.user.id

    if @ticket.save
      redirect_to support_tickets_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def authorize_ticket_access
    unless UserPolicy.new.can_access_ticket?(@ticket)
      render file: "public/404.html", status: :forbidden
    end
  end

  def ticket_params
    params.expect(ticket: [ :title, :description ])
  end
end

app/controllers/support_controller.rb
class SupportController < ApplicationController
  allow_unauthenticated_access

  def index
  end
end

app/controllers/workspace/tickets_controller.rb
class Workspace::TicketsController < WorkspaceController
  before_action :set_ticket, only: %i[ edit update destroy ]
  before_action :load_available_statuses
  before_action :load_available_requesters, only: %i[ new create edit update ]
  before_action :set_status, only: %i[ edit update ]
  before_action :require_admin, only: :destroy
  def index
    @tickets = Ticket.order(:id).page(params[:page]).per(10)
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to workspace_tickets_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @comments = @ticket.comments.all.includes(:user)
    @comment = @ticket.comments.build
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to workspace_tickets_path
    else
      @comments = @ticket.comments.all.includes(:user)
      @comment = @ticket.comments.build
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @ticket.destroy
    redirect_to workspace_tickets_path
  end

  private
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def load_available_statuses
    @statuses = Status.all
  end

  def load_available_requesters
    @requesters = User.all
  end

  def set_status
    @status = @ticket.status.name
  end

  def ticket_params
      params.expect(ticket: [ :title, :description, :status_id, :assigned_agent_id, :requester_id ])
  end

  def require_admin
    unless ::UserPolicy.new.is_admin?
      render file: "public/404.html", status: :forbidden
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/support/tickets/_form_comment.html.erb
<%= turbo_frame_tag "comment-form" do %>
  <%= form_with model: [@ticket, @comment], url: support_ticket_comments_path(@ticket), method: :post, local: true do |form| %>
    <div class="space-y-4 max-w-3xl mx-auto w-full">
      <%= form.text_area :content, rows: 4, maxlength: 9810, size: 90, value: "", class: "border border-gray-300 text-sm text-zinc-50 rounded-lg focus:ring-indigo-600 focus:border-indigo-600 block p-2.5 w-full text-sm text-gray-900 rounded-lg focus:ring-blue-500 focus:border-blue-500 placeholder-gray-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "Write a comment..." %>
      <%# Ensures the text box is cleared after submission by preventing persistence of previous content %>
      <%= form.submit "Add Comment", class: "text-zinc-50 border-indigo-900 border-2 bg-indigo-950 hover:bg-indigo-900 focus:ring-indigo-600 focus:border-indigo-600 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
    </div>
  <% end %>
<% end %>

app/views/support/tickets/_form_ticket.html.erb
<div class="p-2 sm:p-6 md:px-12 space-y-8 relative overflow-x-auto shadow-md sm:rounded-lg border-emerald-900 border-2 max-w-3xl mx-auto w-full text-sm text-left rtl:text-right text-zinc-50 dark:text-gray-400 border-separate border-spacing-x-0 bg-emerald-950">
  <div class="space-y-4">
    <div class="flex justify-between items-center">
      <div class="text-lg font-bold">Ticket Info</div>
      <div class="flex gap-2 mt-4">
        <%= link_to "Cancel", support_tickets_path, class: "text-white border-gray-500 bg-zinc-900 border-2 hover:bg-gray-500 focus:ring-red-600 focus:border-red-600 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
      </div>
    </div>
    <%= form_with model: ticket, url: support_tickets_path, method: :post do |form| %>
      <div class="space-y-4">
        <div class="space-y-2">
          <%= form.label :title, class: "block text-sm font-semibold dark:text-white" do  %>
            <%= label_text_with_required(form, :title) %>
          <% end %>
          <%= form.text_field :title, maxlength: 255, size: 60, class: "border border-gray-300 text-zinc-50 text-sm rounded-lg focus:ring-indigo-600 focus:border-indigo-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        </div>
        <div class="space-y-2">
          <%= form.label :description, class: "block text-sm font-semibold dark:text-white" do  %>
            <%= label_text_with_required(form, :description) %>
          <% end %>
          <%= form.text_field :description, maxlength: 9810, size: 90, class: "border border-gray-300 text-zinc-50 text-sm rounded-lg focus:ring-indigo-600 focus:border-indigo-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        </div>
        <% if @ticket.persisted? %>
          <div class="space-y-2">
            <div class="block text-sm font-semibold dark:text-white">
              Status
            </div>
            <div class="bg-emerald-950 border border-gray-300 text-sm rounded-lg focus:ring-indigo-600 focus:border-indigo-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
              <%= @ticket.status.name %>
            </div>
          </div>
          <div class="space-y-2">
            <div class="block text-sm font-semibold dark:text-white">
              Assigned Agent
            </div>
            <div class="bg-emerald-950 border border-gray-300 text-sm rounded-lg focus:ring-indigo-600 focus:border-indigo-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
              <%= @ticket.assigned_agent&.email_address || "Unassigned" %>
            </div>
          </div> 
        <% end %>  
        <%= form.submit class: "text-white border-indigo-900 border-2 bg-indigo-950 hover:bg-indigo-900 focus:ring-indigo-600 focus:border-indigo-600 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
      </div>
    <% end %>
  </div>
</div>

app/views/support/tickets/_tickets_table.html.erb
<div id="tickets" class="relative overflow-x-auto shadow-md sm:rounded-lg border-emerald-900 border-2">
  <table class="w-full text-sm text-left rtl:text-right text-zinc-50 dark:text-gray-400 border-separate border-spacing-x-0">
    <thead class="text-xs uppercase bg-emerald-950/80 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th scope="col" class="px-3 py-3">
          ID
        </th>
        <th scope="col" class="px-6 py-3">
          Title
        </th>
        <th scope="col" class="px-6 py-3">
          Description
        </th>
        <th scope="col" class="px-6 py-3">
          Status
        </th>
      </tr>
    </thead>
    <tbody>
      <% @tickets.each do |data| %>
        <tr id="row-<%= data.id %>"
            class="bg-emerald-950 dark:bg-gray-800 dark:border-gray-700 hover:bg-emerald-900 dark:hover:bg-gray-600">

          <th scope="row" class="px-3 py-4 font-medium text-zinc-500 whitespace-nowrap dark:text-white hover:text-zinc-50">
            <%= link_to "##{data.id}", support_ticket_path(data) %>
          </th>
          <td class="px-6 py-4"><%= data.title %></td>
          <td class="px-6 py-4"><%= data.description %></td>
          <td class="px-6 py-4"><%= data.status.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <nav class="border-t-1 border-zinc-500 bg-emerald-950 flex items-center flex-column p-3 flex-wrap md:flex-row justify-between" aria-label="Table navigation">
    <div class="text-sm text-zinc-50">
      <%= page_entries_info @tickets, entry_name: 'ticket' %>
    </div>
    <ul class="inline-flex px-3 -space-x-px rtl:space-x-reverse">
      <%= paginate @tickets, :window => 1, :outer_window => 1 %>
    </ul>
  </nav>
</div>

app/views/support/tickets/index.html.erb
<% content_for :title, "Your Tickets" %>

<div class="rounded-lg mx-4 mt-4 px-5 py-2.5 w-fit border-indigo-900 border-2 font-medium text-sm hover:bg-indigo-900 text-zinc-50 bg-indigo-950 shadow-md sm:rounded-lg">
  <%= link_to "New Ticket", new_support_ticket_path %>
</div>



<div class="rounded-sm p-4">
  <%= render "tickets_table" %>
</div>

app/views/support/tickets/new.html.erb
<div class="p-4">
  <%= render "form_ticket", ticket: @ticket %>
</div>

app/views/support/tickets/show.html.erb
<% content_for :title, "##{@ticket.id}" %>

<div class="p-4 space-y-4 xl:flex justify-evenly overflow-y-auto max-h-[calc(100vh-8rem)]">
  <div class="space-y-2">
    <%= render "form_ticket", ticket: @ticket %>
  </div>
  <div class="p-2 sm:p-6 md:px-12 space-y-4 relative overflow-x-auto shadow-md sm:rounded-lg border-emerald-900 border-2 max-w-3xl mx-auto w-full text-sm text-left rtl:text-right text-zinc-50 dark:text-gray-400 border-separate border-spacing-x-0 bg-emerald-950">
    <div class="text-lg font-bold">Comments</div>
    <%= render "form_comment", ticket: @ticket %>
    <br>
    <%= turbo_frame_tag "comments", class: "overflow-auto" do %>
      <div class="space-y-6">
      <% @comments.each do |comment| %>
        <div class="max-w-3xl">
          <span class="text-sm font-normal text-gray-500 dark:text-gray-400">
            <%= comment.user&.email_address || "Unknown" %>: <%= comment.created_at %>
          </span>
          <div class="cursor-default select-text shadow-inner bg-[oklch(0.2_0.04_172.5)]/50 flex flex-col leading-1.5 p-4 text-zinc-100 border border-gray-300 rounded-sm dark:bg-gray-700">
            <p class="text-sm font-normal dark:text-white">
              <%= comment.content %>
            </p>
          </div>
        </div>
      <% end %>
      </div>
    <% end %>
  </div>
</div>