config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resources :statuses

  get "admin", to: "admin#index"

  namespace :admin do
    resources :users do
      member do
        post :resend_activation_email
      end
    end
  end

  get "signup", to: "signup#new"
  post "signup", to: "signup#create"
  get "signup/:id/confirm_email", to: "signup#confirm_email", as: :confirm_email_signup

  root "support#index"
  get "support/home", to: "support#index"
  get "support", to: redirect("support/home")

  namespace :support do
    resources :tickets, only: [ :index, :create, :new, :edit, :show, :update ] do
      resources :comments, only: [ :create ]
    end
  end

  get "workspace/dashboard", to: "workspace#index"
  get "workspace", to: redirect("workspace/dashboard")

  namespace :workspace do
    resources :tickets, only: [ :index, :create, :new, :edit, :show, :update, :destroy ] do
      resources :comments, only: [ :create ]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :tickets, foreign_key: "requester_id"
  has_many :assigned_tickets, class_name: "Ticket", foreign_key: "assigned_agent_id"
  belongs_to :role
  has_many :comments
  before_create :confirmation_token

  validates :email_address, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, uniqueness: true

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  validates :first_name, presence: true
  validates :last_name, presence: true

  PASSWORD_REQUIREMENTS = /\A
    (?=.{8,}) # At least 8 characters long
    (?=.*[a-z]) # Contains at least 1 lowercase letter
    (?=.*[A-Z]) # Contains at least 1 uppercase letter
    (?=.*\d) # Contains at least 1 number
    (?=.*[[:^alnum:]]) # Contains at least 1 symbol
  /x

  validates :password, format: { with: PASSWORD_REQUIREMENTS,
                                 message: "must be 8 or more characters, including lower and upper case letters and at least one number and symbol" },
                                 if: :password_digest_changed?

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!
  end

  private
  def confirmation_token
    if self.confirm_token.blank?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :load_available_roles
  before_action :set_user, only: %i[ edit update ]

  def index
    @users = User.all.order(:id).page(params[:page]).per(10)
  end

  def new
    @user = User.new
    @roles = Role.all
  end

  def create
    @user = User.new(user_params)
    @roles = Role.all
    @role = @user.role.name
    if @user.save
      UserMailer.registration_confirmation(@user).deliver
      redirect_to admin_users_path, notice: "User created successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def resend_activation_email
    user = User.find(params[:id])
    UserMailer.registration_confirmation(user).deliver
    redirect_to admin_users_path, notice: "Activation email resent"
  end

  def edit
    puts @user.inspect
    puts params.inspect
    puts @user.persisted?
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def load_available_roles
    @roles = Role.all
  end

  def user_params
    params.expect(user: [ :email_address, :first_name, :last_name, :role_id, :password, :password_confirmation ])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="p-2 sm:p-6 md:px-12 space-y-8 relative overflow-x-auto shadow-md sm:rounded-lg border-emerald-900 border-2 max-w-3xl mx-auto w-full text-sm text-left rtl:text-right text-zinc-50 dark:text-gray-400 border-separate border-spacing-x-0 bg-emerald-950">
  <div class="space-y-4">
    <div class="flex justify-between items-center">
      <div class="text-lg font-bold">User Info</div>
      <div class="flex gap-2 mt-4">
          <%= link_to "Cancel", :back, class: "text-white border-gray-500 bg-zinc-900 border-2 hover:bg-gray-500 focus:ring-red-600 focus:border-red-600 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
      </div>
    </div>
    <%= form_with model: user,
                  url: user.persisted? ? admin_user_path(user) : admin_users_path,
                  method: user.persisted? ? :patch : :post do |form| %>
      <div class="space-y-4">
        <div class="space-y-2">
          <%= form.label :email_address, class: "block text-sm font-semibold dark:text-white" do  %>
            <%= label_text_with_required(form, :email_address) %>
          <% end %>
          <%= form.text_field :email_address, class: "border border-gray-300 text-zinc-50 text-sm rounded-lg focus:ring-indigo-600 focus:border-indigo-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        </div>
        <div class="space-y-2">
          <%= form.label :first_name, class: "block text-sm font-semibold dark:text-white" do  %>
            <%= label_text_with_required(form, :first_name) %>
          <% end %>
          <%= form.text_field :first_name, class: "border border-gray-300 text-zinc-50 text-sm rounded-lg focus:ring-indigo-600 focus:border-indigo-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        </div>
        <div class="space-y-2">
          <%= form.label :last_name, class: "block text-sm font-semibold dark:text-white" do  %>
            <%= label_text_with_required(form, :last_name) %>
          <% end %>
          <%= form.text_field :last_name, class: "border border-gray-300 text-zinc-50 text-sm rounded-lg focus:ring-indigo-600 focus:border-indigo-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        </div>
        <div class="space-y-2">
          <%= form.label :role_id, class: "block text-sm font-semibold dark:text-white" do  %>
            <%= label_text_with_required(form, :role_id) %>
          <% end %>
          <%= form.collection_select(:role_id, @roles, :id, :name,
                                    {},
                                    { class: "bg-emerald-950 border border-gray-300 text-sm rounded-lg focus:ring-indigo-600 focus:border-indigo-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" }) %>

        </div>
        <div class="space-y-2">
          <%= form.label :password, class: "block text-sm font-semibold dark:text-white" do  %>
            <%= label_text_with_required(form, :password) %>
          <% end %>
          <%= form.text_field :password, type: "password", class: "border border-gray-300 text-zinc-50 text-sm rounded-lg focus:ring-indigo-600 focus:border-indigo-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        </div>
        <div class="space-y-2">
          <%= form.label :password_confirmation, class: "block text-sm font-semibold dark:text-white" do  %>
            <%= label_text_with_required(form, :password_confirmation) %>
          <% end %>
          <%= form.text_field :password_confirmation, type: "password", class: "border border-gray-300 text-zinc-50 text-sm rounded-lg focus:ring-indigo-600 focus:border-indigo-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        </div>
      <%= form.submit class: "text-white border-indigo-900 border-2 bg-indigo-950 hover:bg-indigo-900 focus:ring-indigo-600 focus:border-indigo-600 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/_users_table.html.erb
<div class="relative overflow-x-auto shadow-md sm:rounded-lg border-emerald-900 border-2">
  <table class="w-full text-sm text-left rtl:text-right text-zinc-50 dark:text-gray-400 border-separate border-spacing-x-0">
    <thead class="text-xs uppercase bg-emerald-950/80 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th scope="col" class="px-3 py-3">
          ID
        </th>
        <th scope="col" class="px-6 py-3">
          Name
        </th>
        <th scope="col" class="px-6 py-3">
          Email Address
        </th>
        <th scope="col" class="px-6 py-3">
          Role
        </th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |data| %>
        <tr id="row-<%= data.id %>"
            class="bg-emerald-950 dark:bg-gray-800 dark:border-gray-700 hover:bg-emerald-900 dark:hover:bg-gray-600">

          <th scope="row" class="px-3 py-4 font-medium text-zinc-500 whitespace-nowrap dark:text-white hover:text-zinc-50">
            <%= link_to "##{data.id}", edit_admin_user_path(data) %>
          </th>
          <td class="px-6 py-4"><%= data.first_name + " " + data.last_name %></td>
          <td class="px-6 py-4"><%= data.email_address %></td>
          <td class="px-6 py-4"><%= data.role.name %></td>
          <td><%= link_to "Edit", edit_admin_user_path(data) %>
          <td><%= button_to "Delete", admin_user_path(data), method: :delete, data: { turbo_confirm: "Are you sure?" } %></td>
          <td class="px-6 py-4">
            <% if !data.email_confirmed? %>
              <%= button_to "Resend Activation Email", resend_activation_email_admin_user_path(data), method: :post %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <nav class="border-t-1 border-zinc-500 bg-emerald-950 flex items-center flex-column p-3 flex-wrap md:flex-row justify-between" aria-label="Table navigation">
    <div class="text-sm text-zinc-50">
      <%= page_entries_info @users, entry_name: 'user' %>
    </div>
    <ul class="inline-flex px-3 -space-x-px rtl:space-x-reverse">
      <%= paginate @users, :window => 1, :outer_window => 1 %>
    </ul>
  </nav>
</div>

app/views/admin/users/edit.html.erb
<% content_for :title, @user.id %>

<div class="p-4">
  <%= render "form", user: @user %>
</div>

app/views/admin/users/index.html.erb
<% content_for :title, "Users" %>

<div class="rounded-lg mx-4 mt-4 px-5 py-2.5 w-fit border-indigo-900 border-2 font-medium text-sm hover:bg-indigo-900 text-zinc-50 bg-indigo-950 shadow-md sm:rounded-lg">
  <%= link_to "New", new_admin_user_path %>
</div>

<div class="rounded-sm p-4">
  <%= render "users_table" %>
</div>

app/views/admin/users/new.html.erb
<% content_for :title, "New User" %>

<div class="p-4">
  <%= render "form", user: @user %>
</div>