config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resources :statuses

  get "admin", to: "admin#index"

  namespace :admin do
    resources :users do
      member do
        post :resend_activation_email
      end
    end
  end

  get "signup", to: "signup#new"
  post "signup", to: "signup#create"
  get "signup/:id/confirm_email", to: "signup#confirm_email", as: :confirm_email_signup

  root "support#index"
  get "support/home", to: "support#index"
  get "support", to: redirect("support/home")

  namespace :support do
    resources :tickets, only: [ :index, :create, :new, :edit, :show, :update ] do
      resources :comments, only: [ :create ]
    end
  end

  get "workspace/dashboard", to: "workspace#index"
  get "workspace", to: redirect("workspace/dashboard")

  namespace :workspace do
    resources :tickets, only: [ :index, :create, :new, :edit, :show, :update, :destroy ] do
      resources :comments, only: [ :create ]
    end
  end
end

app/views/layouts/_navbar.html.erb
<div class="bg-zinc-950 dark:bg-gray-900 shadow-md shadow-zinc-950/50 h-full" data-controller="dropdown">
  <div class="flex flex-wrap items-center justify-between mx-auto p-4">
    <a class="flex items-center space-x-3 rtl:space-x-reverse">
      <span class="pl-2 self-center text-2xl font-semibold whitespace-nowrap text-zinc-200 dark:text-white">
        <%= content_for?(:title) ? yield(:title) : "" %>
      </span>
    </a>
    <div class="relative flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
      <!-- User Button -->
      <% if authenticated? %>
        <button type="button"
                data-testid="profile-menu"
                class="flex items-center justify-center text-sm rounded-full size-10
                      bg-zinc-950 outline-2 outline-zinc-200
                      hover:bg-emerald-900 dark:hover:bg-emerald-800
                        transition-colors duration-250"
                data-action="click->dropdown#toggle">
          <span class="sr-only">Open user menu</span>
          <svg xmlns="http://www.w3.org/2000/svg"
               viewBox="0 0 24 24"
               class="size-8 fill-zinc-200">
            <path fill-rule="evenodd"
                  d="M7.5 6a4.5 4.5 0 1 1 9 0 4.5 4.5 0 0 1-9 0ZM3.751 20.105a8.25 8.25 0 0 1 16.498 0 .75.75 0 0 1-.437.695A18.683 18.683 0 0 1 12 22.5c-2.786 0-5.433-.608-7.812-1.7a.75.75 0 0 1-.437-.695Z"
                  clip-rule="evenodd"/>
          </svg>
        </button>
      <% end %>

      <!-- Dropdown Menu -->
      <% if authenticated? %>
        <div class="absolute !right-0 !top-[60px] !w-48 bg-zinc-900 divide-y border-1 border-zinc-200 divide-gray-100 rounded-lg shadow-lg shadow-zinc-950/50
                    dark:bg-gray-700 dark:divide-gray-600 !z-[9999] hidden"
            data-dropdown-target="menu">
          <div class="px-4 py-3">
            <span class="block text-sm text-zinc-200 dark:text-white"><%= Current.user.first_name + " " + Current.user.last_name || "" %></span>
            <span class="block text-sm text-zinc-500 truncate dark:text-gray-400"><%= Current.user.email_address || "" %></span>
          </div>
          <ul class="px-2 py-2">
            <li>
              <%= button_to session_path, method: :delete,
                class: "border-none cursor-pointer 
                        block py-2 px-2 text-sm text-zinc-200 hover:bg-zinc-800 rounded-sm
                        dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" do %>
                Sign out
              <% end %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>

    <div class="hidden w-full md:flex md:w-auto md:order-1 ml-auto"
         id="navbar-user">
      <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <% unless authenticated? %>
          <li>
            <%= link_to new_session_path,
              class: "rounded-lg mx-4 mt-4 px-5 py-2.5 w-fit border-cyan-900 border-2 font-medium text-sm hover:bg-cyan-900 text-zinc-50 bg-cyan-950 shadow-md sm:rounded-lg" do %>
              Log in
            <% end %>
          </li>
          <li>
            <%= link_to signup_path,
              class: "rounded-lg mx-4 mt-4 px-5 py-2.5 w-fit border-cyan-900 border-2 font-medium text-sm hover:bg-cyan-900 text-zinc-50 bg-cyan-950 shadow-md sm:rounded-lg" do %>
              Sign up
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<nav id="separator-sidebar"
     class="h-screen overflow-x-visible bg-zinc-950 dark:bg-gray-800 border-r-1 border-zinc-500"
     aria-label="Sidebar">
      
  <!-- Sidebar Links -->
  <div class="h-full pt-[72px] px-2 bg-zinc-950 dark:bg-gray-800">
    <ul class="space-y-2 font-medium">
      <li class="relative group">
        <%= link_to support_home_path, data: { testid: "support-link" }, class: "flex items-center p-2 text-emerald-50 rounded-lg dark:text-white
                                                hover:bg-emerald-800 dark:hover:bg-gray-700 group" do %>
          <svg class="fill-emerald-50 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 
                  group-hover:text-gray-900 dark:group-hover:text-white"
                  aria-hidden="true"
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  class="size-6">
            <path d="M11.47 3.841a.75.75 0 0 1 1.06 0l8.69 8.69a.75.75 0 1 0 1.06-1.061l-8.689-8.69a2.25 2.25 0 0 0-3.182 0l-8.69 8.69a.75.75 0 1 0 1.061 1.06l8.69-8.689Z" />
            <path d="m12 5.432 8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 0 1-.75-.75v-4.5a.75.75 0 0 0-.75-.75h-3a.75.75 0 0 0-.75.75V21a.75.75 0 0 1-.75.75H5.625a1.875 1.875 0 0 1-1.875-1.875v-6.198a2.29 2.29 0 0 0 .091-.086L12 5.432Z" />
          </svg>
        <% end %>
        <div class="absolute left-full top-1/2 -translate-y-1/2 ml-2
                    opacity-0 scale-95 invisible
                    group-hover:opacity-100 group-hover:scale-100 group-hover:visible
                    transition-all duration-200 ease-in-out
                    bg-emerald-900 text-white text-sm px-3 py-1 rounded-sm w-max z-50
                    pointer-events-none">
            Portal
        </div>
      </li>
      <li class="relative group">
        <% if authenticated? && ::UserPolicy.new.global_ticket_scope? %>
          <%= link_to workspace_dashboard_path, data: { testid: "dashboard-link" }, class: "flex items-center p-2 text-emerald-50 rounded-lg dark:text-white
                                                        hover:bg-emerald-800 dark:hover:bg-gray-700 group" do %>
            <svg class="fill-emerald-50 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400
                        group-hover:text-gray-900 dark:group-hover:text-white"
                 aria-hidden="true"
                 xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 24 24"
                 class="size-6">
              <path stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M3.75 6A2.25 2.25 0 0 1 6 3.75h2.25A2.25 2.25 0 0 1 10.5 6v2.25a2.25 2.25 0 0 1-2.25 2.25H6a2.25 2.25 0 0 1-2.25-2.25V6ZM3.75 15.75A2.25 2.25 0 0 1 6 13.5h2.25a2.25 2.25 0 0 1 2.25 2.25V18a2.25 2.25 0 0 1-2.25 2.25H6A2.25 2.25 0 0 1 3.75 18v-2.25ZM13.5 6a2.25 2.25 0 0 1 2.25-2.25H18A2.25 2.25 0 0 1 20.25 6v2.25A2.25 2.25 0 0 1 18 10.5h-2.25a2.25 2.25 0 0 1-2.25-2.25V6ZM13.5 15.75a2.25 2.25 0 0 1 2.25-2.25H18a2.25 2.25 0 0 1 2.25 2.25V18A2.25 2.25 0 0 1 18 20.25h-2.25A2.25 2.25 0 0 1 13.5 18v-2.25Z" />
            </svg>
          <% end %>
          <div class="absolute left-full top-1/2 -translate-y-1/2 ml-2
                      opacity-0 scale-95 invisible
                      group-hover:opacity-100 group-hover:scale-100 group-hover:visible
                      transition-all duration-200 ease-in-out
                      bg-emerald-900 text-white text-sm px-3 py-1 rounded-sm w-max z-50
                      pointer-events-none">
            Dashboard
          </div>
        <% end %>
      </li>
      <li class="relative group">
        <% if authenticated? && ::UserPolicy.new.global_ticket_scope? %>
          <%= link_to workspace_tickets_path, data: { testid: "workspace-link" }, class: "flex items-center p-2 text-emerald-50 rounded-lg dark:text-white
                                                      hover:bg-emerald-800 dark:hover:bg-gray-700 group" do %>
            <svg class="fill-emerald-50 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400
                        group-hover:text-gray-900 dark:group-hover:text-white"
                  aria-hidden="true"
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  class="size-6">
              <path fill-rule="evenodd"
                    d="M1.5 6.375c0-1.036.84-1.875 1.875-1.875h17.25c1.035 0 1.875.84 1.875 1.875v3.026a.75.75 0 0 1-.375.65 2.249 2.249 0 0 0 0 3.898.75.75 0 0 1 .375.65v3.026c0 1.035-.84 1.875-1.875 1.875H3.375A1.875 1.875 0 0 1 1.5 17.625v-3.026a.75.75 0 0 1 .374-.65 2.249 2.249 0 0 0 0-3.898.75.75 0 0 1-.374-.65V6.375Zm15-1.125a.75.75 0 0 1 .75.75v.75a.75.75 0 0 1-1.5 0V6a.75.75 0 0 1 .75-.75Zm.75 4.5a.75.75 0 0 0-1.5 0v.75a.75.75 0 0 0 1.5 0v-.75Zm-.75 3a.75.75 0 0 1 .75.75v.75a.75.75 0 0 1-1.5 0v-.75a.75.75 0 0 1 .75-.75Zm.75 4.5a.75.75 0 0 0-1.5 0V18a.75.75 0 0 0 1.5 0v-.75ZM6 12a.75.75 0 0 1 .75-.75H12a.75.75 0 0 1 0 1.5H6.75A.75.75 0 0 1 6 12Zm.75 2.25a.75.75 0 0 0 0 1.5h3a.75.75 0 0 0 0-1.5h-3Z"
                    clip-rule="evenodd" />
            </svg>
          <% end %>
          <div class="absolute left-full top-1/2 -translate-y-1/2 ml-2
                      opacity-0 scale-95 invisible
                      group-hover:opacity-100 group-hover:scale-100 group-hover:visible
                      transition-all duration-200 ease-in-out
                      bg-emerald-900 text-white text-sm px-3 py-1 rounded-sm w-max z-50
                      pointer-events-none">
            Tickets
          </div>
        <% end %>
      </li>
      <li class="relative group">
        <% if authenticated? && ::UserPolicy.new.can_access_admin_portal? %>
          <%= link_to admin_path, data: { testid: "admin-link" }, class: "flex items-center p-2 text-emerald-50 rounded-lg dark:text-white
                                          hover:bg-emerald-800 dark:hover:bg-gray-700 group" do %>
            <svg class="fill-emerald-50 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400
                        group-hover:text-gray-900 dark:group-hover:text-white"
                 aria-hidden="true"
                 xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 24 24"
                 class="size-6">
              <path fill-rule="evenodd"
                    d="M11.828 2.25c-.916 0-1.699.663-1.85 1.567l-.091.549a.798.798 0 0 1-.517.608 7.45 7.45 0 0 0-.478.198.798.798 0 0 1-.796-.064l-.453-.324a1.875 1.875 0 0 0-2.416.2l-.243.243a1.875 1.875 0 0 0-.2 2.416l.324.453a.798.798 0 0 1 .064.796 7.448 7.448 0 0 0-.198.478.798.798 0 0 1-.608.517l-.55.092a1.875 1.875 0 0 0-1.566 1.849v.344c0 .916.663 1.699 1.567 1.85l.549.091c.281.047.508.25.608.517.06.162.127.321.198.478a.798.798 0 0 1-.064.796l-.324.453a1.875 1.875 0 0 0 .2 2.416l.243.243c.648.648 1.67.733 2.416.2l.453-.324a.798.798 0 0 1 .796-.064c.157.071.316.137.478.198.267.1.47.327.517.608l.092.55c.15.903.932 1.566 1.849 1.566h.344c.916 0 1.699-.663 1.85-1.567l.091-.549a.798.798 0 0 1 .517-.608 7.52 7.52 0 0 0 .478-.198.798.798 0 0 1 .796.064l.453.324a1.875 1.875 0 0 0 2.416-.2l.243-.243c.648-.648.733-1.67.2-2.416l-.324-.453a.798.798 0 0 1-.064-.796c.071-.157.137-.316.198-.478.1-.267.327-.47.608-.517l.55-.091a1.875 1.875 0 0 0 1.566-1.85v-.344c0-.916-.663-1.699-1.567-1.85l-.549-.091a.798.798 0 0 1-.608-.517 7.507 7.507 0 0 0-.198-.478.798.798 0 0 1 .064-.796l.324-.453a1.875 1.875 0 0 0-.2-2.416l-.243-.243a1.875 1.875 0 0 0-2.416-.2l-.453.324a.798.798 0 0 1-.796.064 7.462 7.462 0 0 0-.478-.198.798.798 0 0 1-.517-.608l-.091-.55a1.875 1.875 0 0 0-1.85-1.566h-.344ZM12 15.75a3.75 3.75 0 1 0 0-7.5 3.75 3.75 0 0 0 0 7.5Z"
                    clip-rule="evenodd" />
            </svg>
          <% end %>
          <div class="absolute left-full top-1/2 -translate-y-1/2 ml-2
                  opacity-0 scale-95 invisible
                  group-hover:opacity-100 group-hover:scale-100 group-hover:visible
                  transition-all duration-200 ease-in-out
                  bg-emerald-900 text-white text-sm px-3 py-1 rounded-sm w-max z-50
                  pointer-events-none">
            Admin
          </div>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ticketing System" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |key, message| %>
      <div class="flash <%= key %>">
        <%= message %>
      </div>
    <% end %>

    <div class="flex flex-1">
      <aside class="sticky top-0 z-100"> <%# z-100 ensures tooltip appears over all other elements %>
        <%= render "layouts/sidebar" %>
      </aside>

      <div class="flex-1 flex flex-col">
        <header class="sticky top-0 h-16 z-50">
          <%= render "layouts/navbar" %>
        </header>

        <main class="flex-1 bg-zinc-900 p-2 overflow-y-auto">
          <%= yield %>
        </main>
      </div>
    </div>
  </body>
</html>